version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - be-cache:/data
    # command: redis-server --requirepass redispassword # Use with redis auth
    networks: 
      - backend
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    volumes:  
      - ./be-db:/data/db  
    ports:  
      - 27017:27017    
    networks:
      - nestjs-reactjs-starter
  backend:
    image: node:14-alpine
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./backend/:/usr/src/app
    networks:
      - nestjs-reactjs-starter
    command: npm start
  frontend:
    image: node:14-alpine
    container_name: frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3001:3001"
    working_dir: /usr/src/app
    volumes:
      - ./frontend/:/usr/src/app
    networks:
      - nestjs-reactjs-starter
    command: npm start
volumes:
  be-cache:
  be-db:
networks:
  nestjs-reactjs-starter:
    driver: bridge